version: "3"
services:
  app-frontend:
    image: rekakr/app-frontend
    ports:
      - 3000:3000
    networks:
      - app-network

  app-backend:
    image: rekakr/app-backend
    environment:
      - MONGO_CONNECTION=${MONGO_CONNECTION}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - 3001:3001
    networks:
      - app-network

networks:
  app-network:
    driver: bridge